sales:
  outputs:
    dev:
      dataset: json_dbt
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: SA.json
      location: US
      method: service-account
      priority: interactive
      project: gen-lang-client-0721975631
      threads: 1
      type: bigquery
    prod:
      dataset: json_dbt
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: SA.json
      location: US
      method: service-account
      priority: interactive
      project: gen-lang-client-prod
      threads: 1
      type: bigquery
  target: dev
